version: '3'
services:
    reverse-proxy:
        image: traefik:v2.4
        command: --api.insecure=true --providers.docker
        ports: 
            - "80:80"
            - "8080:8080"
        depends_on:
            - login
            - profile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            # - ./traefik.toml:/etc/traefik/traefik.toml

    login:
        build: ./login
        depends_on: 
            - db
            - redis
        container_name: login
        # ports:
        #     - "8000:8000"
        environment: 
            - ACCESS_SECRET=${ACCESS_SECRET}
            - REFRESH_SECRET=${REFRESH_SECRET}
            - MONGO_URI=mongodb://db:27017
            - REDIS_DSN=redis:6379
        labels: 
            - "traefik.http.routers.profile.rule=PathPrefix(`/login`) || PathPrefix(`/logout`) || PathPrefix(`/signup`) || PathPrefix(`/token/refresh`)"
            - "traefik.http.services.profile.loadbalancer.server.port=8000"
    
    profile:
        build: ./profile
        depends_on: 
            - db
            - redis
        container_name: profile
        # ports:
        #     - "8001:8001"
        environment: 
            - ACCESS_SECRET=${ACCESS_SECRET}
            - REFRESH_SECRET=${REFRESH_SECRET}
            - MONGO_URI=mongodb://db:27017
            - REDIS_DSN=redis:6379
        labels: 
            - "traefik.http.routers.login.rule=PathPrefix(`/profile`)"
            - "traefik.http.services.login.loadbalancer.server.port=8001"

    db:
        image: mongo:latest
        ports: 
            - "27017:27017"
        container_name: db
        volumes: 
            - ./mongo/data:/data/db
    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        container_name: my_redis
    whoami:
        # A container that exposes an API to show its IP address
        image: traefik/whoami
        labels:
        - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"